version: '3.8'

services:
  apiGatewayZuul:
    build:
      context: .
      dockerfile: Dockerfile-apiGatewayZuul
    container_name: apiGatewayZuul_container
    ports:
      - "8765:8765" # Mapeamento de porta para acessar o serviço apiGatewayZuul
    environment:
      - SPRING_APPLICATION_NAME=apiGatewayZuul
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaServer:8761/eureka
      - SPRING_CLOUD_GATEWAY_HTTPCLIENT_CONNECT-TIMEOUT=1000
      - SPRING_CLOUD_GATEWAY_HTTPCLIENT_RESPONSE-TIMEOUT=5s
    depends_on:
      - eurekaServer

  eurekaServer:
    build:
      context: .
      dockerfile: Dockerfile-eurekaServer
    container_name: eurekaServer_container
    ports:
      - "8761:8761" # Mapeamento de porta para acessar o serviço eurekaServer

  userManagement:
    image: userManagement_image
    container_name: userManagement_container
    environment:
      - SPRING_APPLICATION_NAME=userManagement
      # Adicione outras variáveis de ambiente necessárias conforme especificado no application.properties do userManagement

  productRegistry:
    image: productRegistry_image
    container_name: productRegistry_container
    environment:
      - SPRING_APPLICATION_NAME=productRegistry
      # Adicione outras variáveis de ambiente necessárias conforme especificado no application.properties do productRegistry

  orderManagement:
    image: orderManagement_image
    container_name: orderManagement_container
    environment:
      - SPRING_APPLICATION_NAME=orderManagement
      # Adicione outras variáveis de ambiente necessárias conforme especificado no application.properties do orderManagement

  DeliverLogistic:
    image: DeliverLogistic_image
    container_name: DeliverLogistic_container
    environment:
      - SPRING_APPLICATION_NAME=DeliverLogistic
      # Adicione outras variáveis de ambiente necessárias conforme especificado no application.properties do DeliverLogistic
